export const HomeStyles = {
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingVertical: 100,
    },
    button: {
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 10,
      elevation: 3,
      backgroundColor: '#BEDEFF',
      borderWidth: 2,
      height: 100,
      width: 100,
      margin:2,
    },
    buttonText: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: 'bold',
      letterSpacing: 0.25,
      color: 'black',
      marginBottom: 5,
    },
    text: {
      fontSize: 22,
      lineHeight: 30,
      fontWeight: 'bold',
      letterSpacing: 0.25,
      color: 'black',
      marginBottom: 10,
    },
  };
